### ISSUE TITLE
Creating multiple pages

### ISSUE THREAD

**Issue by matthewgallo** [dutchwebworks/generator-dwwpugsite#2]
Hello, I am having trouble creating multiple pages (pug/html files). Do you have any documentation on how to do that? I have looked but couldn't seem to find anything. Thanks so much!

**Comment by dutchwebworks** [comment]
Hi @matthewgallo,

Thank you for using my Yeoman Generator.

* You'll need to have Grunt (or Gulp) **watch** your files during development of your site. Like described in the `/README.md` file, by running the `grunt serve` or `gulp serve` on the command-line (MS-DOS window / Terminal). This makes sure any changed or new  `*.pug` files are compiled to it's HTML equivalent in the `dist/` directory. This `dist/` directory is served to the web browser.
* To add a new page(s): either duplicate the `src/index.pug` file or add a new Pug file, like: `about.pug` to the `src/` directory. Make sure that that pug file uses a **master** page (it's surrounding HTML) using the Pug **extends** line (see `src/index.pug`).
* Then add some new Pug markup to this new `src/about.pug` file, save the file, now Grunt/Gulp compiles that Pug file as HTML to `dist/about.html`. Now open that file in the web browser. 

See the online PugJS documentation, section 'Language Reference' in the right sidebar on https://pugjs.org/ for more info on Pug syntax.

Good luck and kind regards from the Netherlands,
Dennis
